export const PLACE_CATEGORIES = [
    { value: "bank", label: "Bank" },
    { value: "hospital", label: "Hospital" },
    { value: "government", label: "Government Office" },
    { value: "courthouse", label: "Courthouse" },
    { value: "police", label: "Police Station" },
    { value: "college", label: "College" },
    { value: "school", label: "School" },
    { value: "post_office", label: "Post Office" },
    { value: "passport_office", label: "Passport Office" },
    { value: "railway_station", label: "Railway Station" },
    { value: "bus_station", label: "Bus Station" },
    { value: "restaurant", label: "Restaurant" },
    { value: "cafe", label: "Cafe" },
    { value: "mall", label: "Mall" },
    { value: "electricity_office", label: "Electricity Office" },
    { value: "water_office", label: "Water Office" },
    { value: "gas_agency", label: "Gas Agency" },
    { value: "telecom_office", label: "Telecom Office" }
];

export const PRESET_COUNTERS = [
    "General",
    "Token Counter",
    "Help Desk",
    "Reception",
    "Information Desk",
    "Customer Service",
    "Customer Care",
    "Enquiry",
    "Support Desk",
    "Registration",
    "Billing",
    "Payment Counter",
    "Cash",
    "Cash Deposit",
    "Cash Withdrawal",
    "Account Opening",
    "Loan Desk",
    "KYC Verification",
    "Document Verification",
    "Appointment Desk",
    "Query Resolution",
    "Complaint Desk",
    "Feedback Counter",

    "OPD",
    "Emergency",
    "Doctor Consultation",
    "Pharmacy",
    "Lab Test",
    "X-Ray",
    "Radiology",
    "Medical Records",
    "Insurance Desk",
    "Discharge Desk",

    "Application Submission",
    "Certificate Collection",
    "ID Services",
    "Passport Services",
    "License Desk",
    "Revenue Desk",
    "Property Services",
    "Birth & Death Registration",
    "Grievance Cell",
    "Public Services",

    "Admissions",
    "Fees Counter",
    "Examination",
    "Certificates",
    "Scholarship Desk",
    "Student Affairs",
    "Administration",
    "Library",
    "Hostel Office",

    "Ticket Booking",
    "Reservation",
    "Refund Counter",
    "Lost & Found",
    "Meter Services",
    "New Connection",
    "Bill Payment",
    "Service Request",

    "Order Counter",
    "Takeaway",
    "Dine-In",
    "Pickup Counter",
    "Returns",
    "Exchange",
    "Membership Desk",
    "Gift Counter",

    "Passbook Printing",
    "Cheque Deposit",
    "Forex Counter",
    "Locker Services",
    "Relationship Manager"
];
